pejapp_django/pejapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='post-list'),
    path('register/', views.register, name='register'),
    path('login/', views.custom_login, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('profile/<str:username>/', views.user_profile, name='user-profile'),
    path('post/new/', views.post_create, name='post-create'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/<int:pk>/update/', views.post_update, name='post-update'),
    path('post/<int:pk>/delete/', views.post_delete, name='post-delete'),
    path('search/', views.search, name='search'),
]

pejapp_django/pejapp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("pejapp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pejapp_django/pejapp/models.py
from django.db import models
from django.contrib.auth.models import User
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.user.username}'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class Post(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    modified_flag = models.BooleanField(default=False)
    original_content = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.author.username} Post id {self.id}'

pejapp_django/pejapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Post

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio']

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title','content']

pejapp_django/pejapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, PostForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .models import Post
from django.contrib.auth.models import User
from django.db.models import Q
from django.utils import timezone
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from datetime import datetime, timedelta
from django.http import JsonResponse

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'pejapp/register.html', {'form': form})

def user_profile(request, username=None):
    if username:
        user = get_object_or_404(User, username=username)
    else:
        user = request.user

    if request.user.is_authenticated and request.method == 'POST' and user == request.user:
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('user-profile', username=request.user.username)
    else:
        u_form = UserUpdateForm(instance=request.user) if request.user.is_authenticated else None
        p_form = ProfileUpdateForm(instance=request.user.profile) if request.user.is_authenticated else None

    search_query = request.GET.get('search', '')
    start_date = request.GET.get('start_date', '')
    end_date = request.GET.get('end_date', '')
    sort_order = request.GET.get('sort', 'desc')

    posts = user.post_set.all()

    if search_query:
        posts = posts.filter(content__icontains=search_query)

    if start_date:
        posts = posts.filter(date_posted__gte=start_date)

    if end_date:
        posts = posts.filter(date_posted__lte=end_date)

    if sort_order == 'asc':
        posts = posts.order_by('date_posted')
    else:
        posts = posts.order_by('-date_posted')

    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'profile_user': user,
        'u_form': u_form,
        'p_form': p_form,
        'posts': posts,
        'sort_order': sort_order,
    }

    return render(request, 'pejapp/user_profile.html', context)

def home(request):
    posts = Post.objects.all().order_by('-date_posted')
    paginator = Paginator(posts, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'pejapp/post_list.html', {'posts': posts})
    return render(request, 'pejapp/home.html', {'posts': posts})

def search(request):
    query = request.GET.get('q', '')
    post_page = request.GET.get('post_page', 1)
    user_page = request.GET.get('user_page', 1)

    posts = Post.objects.filter(Q(title__icontains=query) | Q(content__icontains=query)).order_by('-date_posted')
    users = User.objects.filter(Q(username__icontains=query) | Q(email__icontains=query))

    post_paginator = Paginator(posts, 5)
    user_paginator = Paginator(users, 5)

    try:
        posts = post_paginator.page(post_page)
    except PageNotAnInteger:
        posts = post_paginator.page(1)
    except EmptyPage:
        posts = post_paginator.page(post_paginator.num_pages)

    try:
        users = user_paginator.page(user_page)
    except PageNotAnInteger:
        users = user_paginator.page(1)
    except EmptyPage:
        users = user_paginator.page(user_paginator.num_pages)

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        if 'post_page' in request.GET:
            return render(request, 'pejapp/post_search_results.html', {'posts': posts, 'query': query})
        elif 'user_page' in request.GET:
            return render(request, 'pejapp/user_search_results.html', {'users': users, 'query': query})

    context = {
        'query': query,
        'posts': posts,
        'users': users,
    }

    return render(request, 'pejapp/search_results.html', context)

@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post-list')
    else:
        form = PostForm()
    return render(request, 'pejapp/create_post.html', {'form': form})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'pejapp/post_detail.html', {'post': post})

@login_required
def post_update(request, pk):
    post = Post.objects.get(pk=pk)
    prev_content = post.content
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post.modified_flag = True
            post.last_modified = timezone.now()
            post.original_content = prev_content
            form.save()
            return redirect('user-profile', username=request.user.username)
    else:
        form = PostForm(instance=post)
    return render(request, 'pejapp/create_post.html', {'form': form})

@login_required
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('user-profile', username=request.user.username)

def custom_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'You have been logged in successfully.')
                return redirect('post-list')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid username or password.')
    else:
        form = AuthenticationForm()
    return render(request, 'pejapp/login.html', {'form': form})

def custom_logout(request):
    logout(request)
    messages.success(request, 'You have been logged out successfully.')
    return redirect('post-list')

pejapp_django/pejapp/templates/pejapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/40f7a5c3eb.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="'text/css" media="all"/>
    <title>Pejapp</title>
</head>

<body>
    <nav class="py-2 bg-body-tertairy border-bottom">
        <div class="container d-flex flex-wrap">
            <ul class="nav me-auto">
                <li class="nav-item">
                    <a class="nav-link link-body-emphasis px-2 active" href="{% url 'post-list' %}">Strona główna</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link link-body-emphasis px-2" href="{% url 'post-create' %}">Dodaj Posta</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link link-body-emphasis px-2" href="#">O nas</a>
                </li>
            </ul>
            <ul class="nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link link-body-emphasis px-2" href="{% url 'profile' %}">
                            Profil
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-body-emphasis px-2" href="{% url 'logout' %}">Wyloguj się</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link link-body-emphasis px-2" href="{% url 'login' %}">Zaloguj się</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-body-emphasis px-2" href="{% url 'register' %}">Zarejestruj się</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <header class="py-3 mb-4 border-bottom">
        <div class="container d-flex flex-wrap justify-content-center">
            <a href="{% url 'post-list' %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-envelope-open-heart" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8.47 1.318a1 1 0 0 0-.94 0l-6 3.2A1 1 0 0 0 1 5.4v.817l3.235 1.94a2.8 2.8 0 0 0-.233 1.027L1 7.384v5.733l3.479-2.087q.224.414.558.83l-4.002 2.402A1 1 0 0 0 2 15h12a1 1 0 0 0 .965-.738l-4.002-2.401q.334-.418.558-.831L15 13.117V7.383l-3.002 1.801a2.8 2.8 0 0 0-.233-1.026L15 6.217V5.4a1 1 0 0 0-.53-.882zM7.06.435a2 2 0 0 1 1.882 0l6 3.2A2 2 0 0 1 16 5.4V14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5.4a2 2 0 0 1 1.059-1.765zM8 7.993c1.664-1.711 5.825 1.283 0 5.132-5.825-3.85-1.664-6.843 0-5.132"/>
                  </svg>
                &nbsp;
                <span class="fs-4">Pejapp</span>
            </a>
            <form class="d-flex" action="{% url 'search' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Szukaj" aria-label="Szukaj" name="q">
                <button class="btn btn-outline-success" type="submit">Szukaj</button>
            </form>
        </div>
    </header>

    <div class="container mt-3">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags == 'success' %}alert-success{% elif message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

pejapp_django/pejapp/templates/pejapp/create_post.html
{% extends 'pejapp/base.html' %}
{% block content %}
  <h2>Dodaj nowy post</h2>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Dodaj</button>
  </form>
{% endblock %}

pejapp_django/pejapp/templates/pejapp/home.html
{% extends 'pejapp/base.html' %}
{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h2 class="text-left mb-4" style="font-family: 'Arial Black', sans-serif; color: #007bff;">Wszystkie posty</h2>
      <div id="post-list">
        {% include 'pejapp/post_list.html' %}
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const postDates = document.querySelectorAll('.post-date');
    postDates.forEach(function (dateElement) {
      const date = new Date(dateElement.getAttribute('data-date'));
      const now = new Date();
      const diff = Math.abs(now - date);
      const diffSeconds = Math.floor(diff / 1000);
      const diffMinutes = Math.floor(diff / (1000 * 60));
      const diffHours = Math.floor(diff / (1000 * 60 * 60));
      const diffDays = Math.floor(diff / (1000 * 60 * 60 * 24));
      const diffWeeks = Math.floor(diff / (1000 * 60 * 60 * 24 * 7));

      let formattedDate;
      if (diffSeconds < 60) {
        formattedDate = `${diffSeconds} sekund temu`;
      } else if (diffMinutes < 60) {
        formattedDate = `${diffMinutes} minut temu`;
      } else if (diffHours < 24) {
        formattedDate = `${diffHours} godzin temu`;
      } else if (diffDays < 7) {
        formattedDate = `${diffDays} dni temu`;
      } else {
        formattedDate = date.toLocaleDateString('pl-PL', {
          year: 'numeric',
          month: 'long',
          day: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        });
      }

      dateElement.textContent = formattedDate;
    });

    document.querySelectorAll('.pagination a').forEach(function (link) {
      link.addEventListener('click', function (e) {
        e.preventDefault();
        const page = this.getAttribute('data-page');
        fetch(`?page=${page}`, {
          headers: {
            'X-Requested-With': 'XMLHttpRequest'
          }
        })
        .then(response => response.text())
        .then(html => {
          document.getElementById('post-list').innerHTML = html;
          // Re-attach event listeners to new pagination links
          document.querySelectorAll('.pagination a').forEach(function (link) {
            link.addEventListener('click', function (e) {
              e.preventDefault();
              const page = this.getAttribute('data-page');
              fetch(`?page=${page}`, {
                headers: {
                  'X-Requested-With': 'XMLHttpRequest'
                }
              })
              .then(response => response.text())
              .then(html => {
                document.getElementById('post-list').innerHTML = html;
              });
            });
          });
        });
      });
    });
  });
</script>
{% endblock %}

pejapp_django/pejapp/templates/pejapp/login.html
{% extends 'pejapp/base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <main class="form-signin">
        <form method="post" novalidate>
          {% csrf_token %}
          <h1 class="h3 mb-3 fw-normal text-center">Proszę zaloguj się</h1>
          <div class="form-floating mb-3">
            <input type="text" name="username" class="form-control" id="id_username" placeholder="Nazwa użytkownika" required>
            <label for="id_username">Nazwa użytkownika</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" name="password" class="form-control" id="id_password" placeholder="Hasło" required>
            <label for="id_password">Hasło</label>
          </div>
          <button class="btn btn-primary w-100 py-2" type="submit">Zaloguj się</button>
        </form>
      </main>
    </div>
  </div>
</div>
{% endblock %}

pejapp_django/pejapp/templates/pejapp/register.html
{% extends 'pejapp/base.html' %}
{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <main class="form-signin">
        <form method="post" novalidate>
          {% csrf_token %}
          <h1 class="h3 mb-3 fw-normal text-center">Proszę zarejestruj się</h1>
          <div class="form-floating mb-3">
            <input type="text" name="username" class="form-control" id="id_username" placeholder="Nazwa użytkownika" required>
            <label for="id_username">Nazwa użytkownika</label>
          </div>
          <div class="form-floating mb-3">
            <input type="email" name="email" class="form-control" id="id_email" placeholder="Email" required>
            <label for="id_email">Email</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" name="password1" class="form-control" id="id_password1" placeholder="Hasło" required>
            <label for="id_password1">Hasło</label>
            <div id="passwordHelpBlock" class="form-text">
              Twoje hasło musi mieć co najmniej 8 znaków, zawierać wielką literę, małą literę, cyfrę i znak specjalny.
            </div>
          </div>
          <div class="form-floating mb-3">
            <input type="password" name="password2" class="form-control" id="id_password2" placeholder="Potwierdź hasło" required>
            <label for="id_password2">Potwierdź hasło</label>
          </div>
          <button class="btn btn-primary w-100 py-2" type="submit">Zarejestruj się</button>
        </form>
      </main>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const password1 = document.getElementById('id_password1');
    const password2 = document.getElementById('id_password2');
    const passwordHelpBlock = document.getElementById('passwordHelpBlock');

    function validatePassword() {
      const password = password1.value;
      const requirements = [
        { regex: /.{8,}/, message: 'co najmniej 8 znaków' },
        { regex: /[A-Z]/, message: 'wielką literę' },
        { regex: /[a-z]/, message: 'małą literę' },
        { regex: /\d/, message: 'cyfrę' },
        { regex: /[!@#$%^&*(),.?":{}|<>]/, message: 'znak specjalny' }
      ];

      const unmetRequirements = requirements.filter(req => !req.regex.test(password)).map(req => req.message);
      if (unmetRequirements.length > 0) {
        passwordHelpBlock.textContent = `Twoje hasło musi mieć ${unmetRequirements.join(', ')}.`;
        passwordHelpBlock.classList.add('text-danger');
      } else {
        passwordHelpBlock.textContent = 'Twoje hasło spełnia wszystkie wymagania.';
        passwordHelpBlock.classList.remove('text-danger');
        passwordHelpBlock.classList.add('text-success');
      }
    }

    password1.addEventListener('input', validatePassword);
    password2.addEventListener('input', function () {
      if (password1.value !== password2.value) {
        password2.setCustomValidity('Hasła się nie zgadzają');
      } else {
        password2.setCustomValidity('');
      }
    });
  });
</script>
{% endblock %}

pejapp_django/pejapp/templates/pejapp/search_users.html
{% extends 'pejapp/base.html' %}
{% block content %}
  <h2>Wyszukaj użytkowników</h2>
  <form method="get" class="mb-3">
      <input type="text" name="q" placeholder="Wpisz nazwę użytkownika" value="{{ query }}" class="form-control">
      <button type="submit" class="btn btn-primary mt-2">Szukaj</button>
  </form>
  {% if query %}
    <h4>Wyniki wyszukiwania:</h4>
    <ul class="list-group">
      {% for user in users %}
        <li class="list-group-item">{{ user.username }} ({{ user.email }})</li>
      {% empty %}
        <li class="list-group-item">Brak użytkowników spełniających kryteria.</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

pejapp_django/pejapp/templates/pejapp/user_posts.html
{{extends 'pejapp/base.html'}}

{% block title %}Other Users' Posts - Pejapp{% endblock %}
{% block content %}
    <h1>{{post.author}} posts</h1>
    <ul>
        {% for post in posts %}
            <li>
                <p>{{ post.content }}</p>
                <p><strong>Published:</strong> {{ post.published_date }}</p>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

pejapp_django/pejapp/templates/pejapp/user_profile.html
{% extends 'pejapp/base.html' %}
{% block content %}
<div class="container mt-5">
  <h2 class="text-center mb-4">Profil użytkownika {{ profile_user.username }}</h2>
  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4 shadow-sm">
        <div class="card-body text-center">
          <h4 class="card-title" style="color: #007bff; font-weight: bold;">
            {{ profile_user.username }}
          </h4>
          <p class="card-text text-muted">{{ profile_user.email }}</p>
          <p class="card-text text-muted">{{ profile_user.profile.bio|default:"Brak opisu" }}</p>
          {% if user.is_authenticated and user == profile_user %}
            <button class="btn btn-info mt-4" type="button" data-bs-toggle="collapse" data-bs-target="#editProfile" aria-expanded="false" aria-controls="editProfile">
              Edytuj profil <i class="bi bi-caret-down-fill" id="profileIcon" style="color: gray;"></i>
            </button>
          {% endif %}
        </div>
      </div>
      {% if user.is_authenticated and user == profile_user %}
        <div class="collapse" id="editProfile">
          <div class="card mb-4 shadow-sm">
            <div class="card-body">
              <h3 class="card-title">Edytuj profil</h3>
              <form method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                  <input type="text" name="username" class="form-control" id="id_username" placeholder="Nazwa użytkownika" value="{{ u_form.username.value }}">
                  <label for="id_username">Nazwa użytkownika</label>
                </div>
                <div class="form-floating mb-3">
                  <input type="email" name="email" class="form-control" id="id_email" placeholder="Email" value="{{ u_form.email.value }}">
                  <label for="id_email">Email</label>
                </div>
                <div class="form-floating mb-3">
                  <textarea name="bio" class="form-control" id="id_bio" placeholder="Bio">{{ p_form.bio.value }}</textarea>
                  <label for="id_bio">Bio</label>
                </div>
                <button type="submit" class="btn btn-success">Zaktualizuj</button>
              </form>
            </div>
          </div>
        </div>
      {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h3 class="card-title mb-4">Posty</h3>
          <form method="get" class="mb-4">
            <div class="row mb-3">
              <div class="col-md-6">
                <label for="search">Szukaj w postach</label>
                <input type="text" id="search" name="search" placeholder="Szukaj w postach" class="form-control" value="{{ request.GET.search }}">
              </div>
              <div class="col-md-3">
                <label for="start_date">Data początkowa</label>
                <input type="date" id="start_date" name="start_date" class="form-control" value="{{ request.GET.start_date }}">
              </div>
              <div class="col-md-3">
                <label for="end_date">Data końcowa</label>
                <input type="date" id="end_date" name="end_date" class="form-control" value="{{ request.GET.end_date }}">
              </div>
            </div>
            <div class="row mb-3">
              <div class="col-md-6">
                <label for="sort">Sortuj według</label>
                <select id="sort" name="sort" class="form-control">
                  <option value="desc" {% if sort_order == 'desc' %}selected{% endif %}>Od najnowszych</option>
                  <option value="asc" {% if sort_order == 'asc' %}selected{% endif %}>Od najstarszych</option>
                </select>
              </div>
            </div>
            <button type="submit" class="btn btn-success">Zastosuj filtry</button>
            <a href="{% url 'user-profile' profile_user.username %}" class="btn btn-secondary">Usuń filtry</a>
          </form>
          <div id="post-list">
            {% for post in posts %}
              <div class="list-group mb-4">
                <a href="{% url 'user-profile' post.author.username %}" class="list-group-item list-group-item-action">
                  <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ post.title }}</h5>
                    <small>{{ post.date_posted }}</small>
                  </div>
                  <p class="mb-1">{{ post.content|truncatewords:20 }}</p>
                  <small>Opublikowane przez <span class="text-primary">{{ post.author.username }}</span></small>
                </a>
                {% if user.is_authenticated and user == profile_user %}
                  <div class="mt-2 d-flex justify-content-end">
                    <a href="{% url 'post-update' post.pk %}" class="btn btn-sm btn-warning me-2">Edytuj</a>
                    <a href="{% url 'post-delete' post.pk %}" class="btn btn-sm btn-danger">Usuń</a>
                  </div>
                {% endif %}
              </div>
            {% empty %}
              <p class="text-center">Brak postów do wyświetlenia.</p>
            {% endfor %}

            <nav aria-label="Page navigation">
              <ul class="pagination justify-content-center">
                {% if posts.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ posts.previous_page_number }}" data-page="{{ posts.previous_page_number }}">Poprzednia</a>
                  </li>
                {% endif %}
                {% for num in posts.paginator.page_range %}
                  {% if posts.number == num %}
                    <li class="page-item active">
                      <span class="page-link">{{ num }}</span>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ num }}" data-page="{{ num }}">{{ num }}</a>
                    </li>
                  {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?page={{ posts.next_page_number }}" data-page="{{ posts.next_page_number }}">Następna</a>
                  </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    const profileIcon = document.getElementById('profileIcon');
    const editProfile = document.getElementById('editProfile');
    editProfile.addEventListener('shown.bs.collapse', function () {
      profileIcon.classList.remove('bi-caret-down-fill');
      profileIcon.classList.add('bi-caret-up-fill');
    });
    editProfile.addEventListener('hidden.bs.collapse', function () {
      profileIcon.classList.remove('bi-caret-up-fill');
      profileIcon.classList.add('bi-caret-down-fill');
    });

    document.querySelectorAll('.pagination a').forEach(function (link) {
      link.addEventListener('click', function (e) {
        e.preventDefault();
        const page = this.getAttribute('data-page');
        const url = new URL(window.location.href);
        url.searchParams.set('page', page);
        fetch(url, {
          headers: {
            'X-Requested-With': 'XMLHttpRequest'
          }
        })
        .then(response => response.text())
        .then(html => {
          const parser = new DOMParser();
          const doc = parser.parseFromString(html, 'text/html');
          const newPosts = doc.querySelector('#post-list').innerHTML;
          document.getElementById('post-list').innerHTML = newPosts;
          // Re-attach event listeners to new pagination links
          document.querySelectorAll('.pagination a').forEach(function (link) {
            link.addEventListener('click', function (e) {
              e.preventDefault();
              const page = this.getAttribute('data-page');
              const url = new URL(window.location.href);
              url.searchParams.set('page', page);
              fetch(url, {
                headers: {
                  'X-Requested-With': 'XMLHttpRequest'
                }
              })
              .then(response => response.text())
              .then(html => {
                const parser = new DOMParser();
                const doc = parser.parseFromString(html, 'text/html');
                const newPosts = doc.querySelector('#post-list').innerHTML;
                document.getElementById('post-list').innerHTML = newPosts;
              });
            });
          });
        });
      });
    });
  });
</script>
{% endblock %}